### PR TITLE
Sync 1

### PR DESCRIPTION
**Pull request by DrX3D**
Added several new models that were unique to glTF-Sample-Models. Also updates to the generator program to include a list of model extensions (used and required).

### CODE REVIEW

**Comment by DrX3D** [comment]
This needs to be merged before #86. After merging #86 may have synchronization issues that need to be resolved.

**Comment by DrX3D** [comment]
@echadwick-artist, @emackey: Can either of you take a quick look at this PR to make sure the model quality is good. The new models came from glTF-Sample-Models that had not been merged into this repo.

**Comment by DrX3D** [comment]
All models have a new README with a listing of extensions used & required. Some models have updated Metadata file to better describe the license for that model

Listing of new models

- CarbonFibre
- ChairDamaskPurpleGold
- DiffuseTrasmissionPlant
- DiffuseTransmissionTeacup
- DirectionalLight
- PrimitiveModeNormalsTest
- VirtualCity (was VC)
- XmpMetadataRoundedCube

This PR will remain open until 4 Jan 2024 to allow people to comment (due to the holidays).

**Comment by echadwick-artist** [comment]
The changes look good to me. I made a few changes to the models I worked on. Looked at a representative sampling of the MD files, the additions and fixes look good.

**Pull request merged**
