### PR TITLE
Rename VirtualCity files to match asset name

### PR DESCRIPTION
**Pull request by javagl**
The folder name had been changed from `VC` to `VirtualCity`. The individual files still had been called `VC.gltf`/`VC.glb` (as pointed out in https://github.com/KhronosGroup/glTF-Sample-Assets/issues/71#issuecomment-1868449406 ).
 
They are renamed here to `VirtualCity` as well

### CODE REVIEW

**Comment by cx20** [comment]
Perhaps it would be better to modify `model-index.json` as well.

https://github.com/KhronosGroup/glTF-Sample-Assets/blob/43380bb399f5c86acb541ee75af4b5905b6926c5/Models/model-index.json#L1024-L1027

**Comment by javagl** [comment]
@cx20 Some aspects still have to be sorted out here. In the future, the model index _should_ be updated automatically, as of https://github.com/KhronosGroup/glTF-Sample-Assets/issues/54 (yes, that's somehow still on my plate as well, and I should give it higher priority). 

(I'm curious whether you'd use the `model-index.json` for `gltf-test` as well - right now, you're maintaining the README manually, is that correct? If you have any thoughts or ideas for what the CI should or shouldn't do, you can mention them in https://github.com/KhronosGroup/glTF-Sample-Assets/issues/54 . It's important to set things up in a way that allows the results to be easily consumed by projects like yours)

**Comment by DrX3D** [comment]
The name change is also done in (not yet merged) PR #87. Since that brings in a several other models and there is a change to the README to include model extensions, I think it would be better to close this without merging. I am just about to merger #87.

**Comment by DrX3D** [comment]
Had a change of mine. #87 will remain open until 4 Jan 2024 to allow people a chance to comment due to the holidays.

**Pull request closed without merging**
