### PR TITLE
CarConcept asset for The Khronos Group

### PR DESCRIPTION
**Pull request by echadwick-artist**
"Hero" asset generated for The Khronos Group.

variants

### CODE REVIEW

**Comment by echadwick-dgg3d** [comment]
The Khronos 3D Commerce working group requested two additional glTF versions, so there will be four total files:

1. Uncompressed geometry with PNG textures.
2. Draco geometry compression with KTX2 texture compression.
3. Uncompressed geometry with JPG textures.
4. Uncompressed geometry with WEBP textures.

Then we can compare size/quality tradeoffs between the files. I will add a section to the README along with these versions, about compression settings used, and listing the file sizes & memory sizes.

**Comment by echadwick-artist** [comment]
Today the Khronos 3D Commerce working group requested two additional glTF versions, JPG and WEBP, so there would be four total glTF folders:

1. Uncompressed geometry with PNG textures.
2. Draco geometry compression with KTX2 texture compression.
3. Uncompressed geometry with JPG textures.
4. Uncompressed geometry with WEBP textures.

Then we can use these to compare size/quality tradeoffs between the files. I'll try to use the smallest compressions possible with these formats, without introducing too many artifacts. 

Then I will add a section to the README along with these versions, about compression settings used, and listing the file sizes & memory sizes.

**Comment by javagl** [comment]
This _does_ look really cool. And given such a model, I hesitate to ask for "more" (and of course, I have no clue whether that would even be in the budget). But... I think that animations (like "Steer" or "Open doors") could add another layer of "Woah!" here 😎

**Comment by echadwick-artist** [comment]
Thanks Marco! 

I’m thinking of adding animations later with the interactivity extension, tap on a door to open/close it, that kind of thing. 

I originally had animated doors, but with regular looping playback it gets a bit annoying after a while, so I stripped it out.

But anyone is welcome to tweak it however they like! CCBY4 is very permissive.

**Pull request merged**
